### ISSUE TITLE
Can't disable Auth0 on discourse docker setup

### ISSUE THREAD

**Issue by justinsmits** [auth0/discourse-plugin#11]
I installed Auth0 in a discourse docker setup, however I entered in the return url incorrectly in the admin settings, so now I can't login to my site. I am now trying to remove auth0 completely so I can get in or just change the setting manually in some settings file. The two problems I am having is that even though I disabled the plugin from app.yml, it still seems to be redirecting with sso in the url and no dialogue comes up at all. I also don't know where to find the auth0 settings to edit them using a file editor.

**Comment by jfromaniello** [comment]
I so sorry to hear that, 

Discourse store settings on the database. Here is something you can do, from the discourse-docker directory:

~~~bash
./launcher ssh <name of your discourse instance> 

rails c

ss = SiteSetting.where(:name => "auth0_callback_url")[0]
ss[:value] = "http://the-callback-url-you-want"
ss.save!
~~~

If you don't know the name of your discourse instance you can use this trick:

~~~
basename `ls containers/*.yml` .yml
~~~

**Comment by jfromaniello** [comment]
BTW, I will recommend you testing the login flow on a Chrome incognito window, while still keeping your session to discourse on the main chrome window or in another browser.

**Comment by justinsmits** [comment]
Thanks for the help. I have been able to get by that callback url issue, however now when I try to authenticate, I am getting the following error: 

Sorry, there was an error authorizing your Auth0 account. Perhaps you did not approve authorization?

Any ideas?

**Comment by jfromaniello** [comment]
What identity provider are you trying to use?

**Comment by justinsmits** [comment]
Salesforce and then just regular username\password in database.

**Comment by jfromaniello** [comment]
The error you see is from Salesforce. If you click on the Salesforce connection in our dashboard, you will see a "How to obtain a consumer Key".

**Comment by justinsmits** [comment]
What about just logging in using regular username and password?

**Comment by jfromaniello** [comment]
It should work already

**Comment by justinsmits** [comment]
It's not. It gives me the same error:

Sorry, there was an error authorizing your Auth0 account. Perhaps you did not approve authorization?

**Comment by jfromaniello** [comment]
Can you send me an screenshot of the entire browser window on that error page?

Thanks

**Comment by justinsmits** [comment]
Here is a screenshot. Thanks for your help.

[image: Inline image 1]

On Fri, Jan 2, 2015 at 4:57 PM, José F. Romaniello <notifications@github.com

**Comment by jfromaniello** [comment]
I can't see the image.. can you drag&drop it to github directly?

**Comment by justinsmits** [comment]
Let's see if this works:

![image](https://cloud.githubusercontent.com/assets/8573961/5600530/3367ee66-92a1-11e4-9af9-63eb657c060a.png)

**Comment by jfromaniello** [comment]
I think I know what's going on, you have a setting enabled "must_approve_users". Try to disable that either from the UI, or with the trick I explained in the first email:

~~~
./launcher ssh app

rails c

ss = SiteSetting.where(:name => "must_approve_users")[0]
ss[:value] = "f"
ss.save!
~~~

**Comment by justinsmits** [comment]
Nope, still not working.

**Comment by jfromaniello** [comment]
Can you run `echo "SiteSetting.all" | rails c`, then press enter until you rach the end of the table... Copy all settings and send me to jose@auth0.com.

Thank you very much

**Comment by justinsmits** [comment]
Jose, just wanted to let you know that I sent you an email with the settings. Thanks

**Comment by jfromaniello** [comment]
Hi @justinsmits it didn't arrive.

**Comment by justinsmits** [comment]
Can you try sending me an email and then I will reply?
justin.r.smits@gmail.com

**Comment by justinsmits** [comment]
Is there any way to disable to Auth0 plugin completely so I can use the regular discourse authentication while I try to figure this out?

**Comment by justinsmits** [comment]
I was able to get it disabled for now by removing all the lines from the /containers/app.yml file and then rebuilding the application

**Comment by jfromaniello** [comment]
Another way to disable it, is by setting `auth0_client_id` to empty string
