### ISSUE TITLE
Auth0 dialog box is blocking the sign-up form after successful login via Facebook

### ISSUE THREAD

**Issue by heinnge** [auth0/discourse-plugin#12]
![auth0-discourse](https://cloud.githubusercontent.com/assets/14687/9558676/5edd3d34-4e0e-11e5-899a-810050165282.JPG)
as the title implied, the auth0 diaplog box is blocking the sign-up form after the facebook dialog box is closed. 

Is there a way we can skip fill up this sign-up form at all? Just sign-in via Facebook, and already log-in in discourse site?

**Comment by citychanger** [comment]
Thanks! Are you thinking of skipping the sign-up form at some point, per the OP?

**Comment by jfromaniello** [comment]
> Are you thinking of skipping the sign-up form at some point, per the OP?

Sorry guys, I missed this question. I tried at the beginning but I couldn't, this is the place where you resolve things like duplicated nickname and you finish the setup.

Feel free to dig in, the code of the plugin is quite simple. To debug ember follow these steps:

http://stackoverflow.com/questions/23901546/how-to-debug-javascript-code-produced-and-served-by-ember-cli
